# apiVersion: v1
# kind: Service
# metadata:
#   name: client-service
# spec:
#   type: NodePort
#   selector:
#     app: client  # ต้องตรงกับ labels ของ Deployment
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30008  # พอร์ตที่เปิดให้ภายนอกเข้าถึง

apiVersion: v1
kind: Service
metadata:
  name: client-service-chon
  namespace: chon
spec:
  type: ClusterIP
  selector:
    app: client-chon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80